config/routes.rb
RailsApp::Application.routes.draw do
  root :to => 'repos#index'
  resources :repos,
    :only => [:index, :new, :create]
  resources :gits,
    :only => [:show, :destroy]
  resources :svns,
    :only => [:show, :destroy]
  #devise_for :users
  match '*path', :to => 'application#error_404'
end

app/models/git.rb
class Git < ActiveRecord::Base

  class << self

    def generate(id)
      if /[a-z][a-zA-Z0-9_-]+$/ =~ id
        unless /\./ =~ id
          system(RailsApp::Application.config.git_create + " " + RailsApp::Application.config.git_dir + " " + id)
        else
         false
        end
      else
        false
      end
    end

    def destroy(id)
      if /[a-zA-Z0-9_-]+$/ =~ id
        system(RailsApp::Application.config.git_delete + " " + RailsApp::Application.config.git_dir + " " + RailsApp::Application.config.trash_dir + " " + id)
      else
        false
      end
    end

  end

end

app/models/repo.rb
class Repo < ActiveRecord::Base
end

app/models/svn.rb
# -*- coding: utf-8 -*-
class Svn < ActiveRecord::Base

  class << self

    def generate(id)
      if /[a-z][a-zA-Z0-9_-]+$/ =~ id
        unless /\./ =~ id
          system(RailsApp::Application.config.svn_create + " " + RailsApp::Application.config.svn_dir + " " + id)
        else
         false
        end
      else
        false
      end
    end

    def destroy(id)
      if /[a-zA-Z0-9_-]+$/ =~ id
        system(RailsApp::Application.config.svn_delete + " " + RailsApp::Application.config.svn_dir + " " + RailsApp::Application.config.trash_dir + " " + id)
      else
        false
      end
    end
  end

end

app/models/user.rb
#class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable,  #:registerable,
  #       :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  #attr_accessible :email, :password, :password_confirmation, :remember_me, :username

  #validates :username, :uniqueness => { :case_sensitive => false },
  #                     :length     => { :in => 3..15 },
  #                     :format     => { :with => /^[a-z0-9_]+$/ }
  #validates :email,    :uniqueness => { :case_sensitive => false },
  #                     :length     => { :in => 3..420 }

#end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  #def after_sign_in_path_for(resource)
  #  statuses_path || root_path
  #end

  def error_404
    url = request.url 
    render :status=>404,
    :text=>"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL #{url} was not found on this server.</p>
</body></html>
"
  end
end

app/controllers/gits_controller.rb
# -*- coding: utf-8 -*-

class GitsController < ApplicationController
  before_filter :authenticate if RailsApp::Application.config.basic_auth

  def show
    @repo = params[:id]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @repo }
    end
  end

  def destroy
    if request.delete?
      if Git.destroy(params[:id])
        flash[:notice] = "Git リポジトリ " + params[:id] + " は正常に削除されました"
      end
    end

    respond_to do |format|
      format.html { redirect_to(repos_url) }
      format.xml  { head :ok }
    end
  end

  private
  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == RailsApp::Application.config.username &&
      password == RailsApp::Application.config.password
    end
  end
end

app/controllers/repos_controller.rb
# -*- coding: utf-8 -*-

class ReposController < ApplicationController
  before_filter :authenticate if RailsApp::Application.config.basic_auth

  def index
    @git_repos = Dir::entries(RailsApp::Application.config.git_dir).sort
    @svn_repos = Dir::entries(RailsApp::Application.config.svn_dir).sort
    @repos = @git_repos + @svn_repos

    respond_to do |format|
      format.html
      format.json { render json: @repos }
    end
  end

  def new
    respond_to do |format|
      format.html
    end
  end

  def create
    if request.post?
      unless params[:new_git_field].blank?
        if Git.generate(params[:new_git_field])
          flash[:notice] = 'Git リポジトリ ' + params[:new_git_field] + ' は正常に生成されました'
        end
      end
      unless params[:new_svn_field].blank?
        if Svn.generate(params[:new_svn_field])
          flash[:notice] = 'SVN リポジトリ ' + params[:new_svn_field] + ' は正常に生成されました'
        end
      end
    end
    redirect_to(:action => 'index')
  end

  private
  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == RailsApp::Application.config.username &&
      password == RailsApp::Application.config.password
    end
  end
end

app/controllers/svns_controller.rb
# -*- coding: utf-8 -*-

class SvnsController < ApplicationController
  before_filter :authenticate if RailsApp::Application.config.basic_auth

  def show
    @repo = params[:svn_repo]

    respond_to do |format|
      format.html
      format.xml  { render :xml => @repo }
    end
  end

  def destroy
    if request.delete?
      if Svn.destroy(params[:id])
        flash[:notice] = "SVN リポジトリ " + params[:id] + " は正常に削除されました"
      end
    end

    respond_to do |format|
      format.html { redirect_to(repos_url) }
      format.xml  { head :ok }
    end
  end

  private
  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == RailsApp::Application.config.username &&
      password == RailsApp::Application.config.password
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/gits/show.html.haml
- title 'Repository Manager - Detail'

%section#git-show
  .container{:style => "margin-top: 40px; padding-top: 10px"}
    .pageContent
      .show-git
        .container
          .content
            .row
              .span12.offset2
                %h1
                  = "#{params[:id]}.git"
                %table{:class => 'condensed-table bordered-table zebra-striped'}
                  %thead
                    %tr
                      %th{:style => 'style="width: 150px;'}
                        項目
                      %th
                        内容
                  %tbody
                    %tr
                      %td
                        ディレクトリ
                      %td
                        = "#{RailsApp::Application.config.git_dir}/#{params[:id]}.git"
                    %tr
                      %td
                        リポジトリ
                      %td
                        = "ssh://yourname@#{RailsApp::Application.config.hostname}#{RailsApp::Application.config.git_dir}/#{params[:id]}.git"
                    %tr
                      %td
                        最終更新日
                      %td
                        = File::stat(RailsApp::Application.config.git_dir + "/" + params[:id] + ".git/objects").mtime

                .actions
                  = link_to '一覧へ戻る', repos_path, :class => 'btn small'
                  = link_to 'このリポジトリを削除する', params[:id], :data => { :confirm => '本当に削除しますか' }, :method => :delete, :class => 'btn small danger'

app/views/layouts/_footer.html.haml
%footer{:class => "footer"}
  .container
    %p{:class => "pull-right"}
      <a href="/">Back to Top</a>
    %p
      Powered by <a href="http://rubyonrails.org/">Rails 3.2</a>, <a href="http://nodejs.org/">Node.js</a>, <a href="http://haml-lang.com/">Haml</a>, <a href='http://twitter.github.com/bootstrap/'>Bootstrap 1.4.0</a>.<br>
      Code dual licensed under the <a href="http://www.gnu.org/copyleft/gpl.html">GPLv3</a>/<a href="http://www.gnu.org/copyleft/lesser.html">LGPLv3</a>. Documentation licensed under <a rel="license" href="http://creativecommons.org/licenses/by-nd/3.0/">CC (BY-ND) 3.0</a>.

app/views/layouts/_topbar.html.haml
.topbar
  .fill
    .container
      %h3
        %a(href='/')
          Repository
      %ul
        %li= link_to 'Index', repos_path
        %li= link_to 'New', new_repo_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    = stylesheet_link_tag "application"
    -# = stylesheet_link_tag "bootstrap"
    -# = stylesheet_link_tag '/bootstrap/docs/assets/css/docs.css'
    -# = stylesheet_link_tag '/jquery-ui/css/theme/jquery-ui-1.8.16.custom.css'
    = javascript_include_tag "application"
    -# <script type="text/javascript" src="/jquery-ui/js/jquery-1.6.2.min.js"></script>
    -# <script type="text/javascript" src="/jquery-ui/js/jquery-ui-1.8.16.custom.min.js"></script>
    = csrf_meta_tag
    %title
      = yield(:title) || "No Title"
    = yield(:head)

  %body(class='#{controller_name}-#{action_name}-page')
    %section{:id => "topbar"}
      = render :template => 'layouts/_topbar'
    %section{:id => "main"}
      = render :template => 'repos/_portal'
    %section{:id => "footer"}
      = render :template => 'layouts/_footer'

app/views/repos/_form.html.haml
= form_tag({ :controller => "repos", :action => "create", :class => "new_user", :style => "margin:0;padding:0;display:inline" }, { :multipart => true }) do
  %fieldset
    .clearfix
      %label.label_git
        Git
      .input
        = text_field_tag("new_git_field", "")
        %br
    .clearfix
      %label.label_svn
        Subversion
      .input
        = text_field_tag("new_svn_field", "")
        %br
    .actions
      = link_to '一覧に戻る', repos_path, :class => "btn small"
      = submit_tag("作成する", :class => "btn small primary")

app/views/repos/_git.html.haml
%section#index-git
  .container{:style => "margin-top: 40px; padding-top: 10px"}
    .pageContent
      .index-git
        .container
          .content
            .row
              .span12.offset2
                %h1
                  Git リポジトリ一覧
                %table{:class => 'condensed-table zebra-striped'}
                  %thead
                    %tr
                      %th
                        リポジトリ名
                      %th
                        最終更新日
                  %tbody
                    - for git_repo in @git_repos do
                      - unless /\A\./ =~ git_repo
                        %tr
                          %td
                            = link_to(git_repo, { :controller => 'gits', :action => 'show', :id => git_repo.gsub(/\.git\z/, "") })
                          %td
                            = File::stat(RailsApp::Application.config.git_dir + "/" + git_repo + "/objects").mtime.strftime("%Y/%m/%d %X (%a)")

app/views/repos/_portal.html.haml
.container(style='margin-top: 40px; padding-top: 10px')
  - flash.each do |name, msg|
    .alert-message.block-message.success(class='#{name}')= msg

.container
  .pageContent
    = yield

app/views/repos/_svn.html.haml
%section#index-svn
  .container{:style => "margin-top: 40px; padding-top: 10px"}
    .pageContent
      .index-svn
        .container
          .content
            .row
              .span12.offset2
                %h1
                  SVN リポジトリ一覧
                %table{:class => 'condensed-table zebra-striped'}
                  %thead
                    %tr
                      %th
                        リポジトリ名
                      %th
                        最終更新日
                  %tbody
                    - for svn_repo in @svn_repos do
                      - unless /\A\./ =~ svn_repo
                        %tr
                          %td
                            = link_to(svn_repo, { :controller => 'svns', :action => 'show', :id => svn_repo })
                          %td
                            = File::stat(RailsApp::Application.config.svn_dir + "/" + svn_repo + "/db/current").mtime.strftime("%Y/%m/%d %X (%a)")

app/views/repos/index.html.haml
- title 'Repository Manager - Index'

- if @git_repos.length > 2
  = render 'git'
- if @svn_repos.length > 2
  = render 'svn'

%section#new-repo
  .container{:style => "margin-top: 40px; padding-top: 10px"}
    .pageContent
      .row
        .span12.offset2
          .actions
            = link_to 'トップページへ戻る', '/', :class => 'btn small'
            = link_to 'リポジトリ新規作成', new_repo_path, :class => 'btn small primary'

app/views/repos/new.html.haml
- title 'Repository Manager - New'

%section#repo-new
  .container{:style => "margin-top: 40px; padding-top: 10px"}
    %span#new
      .pageContent
        .new
          .container
            .content
              .row
                .span12.offset2
                  %h2
                    リポジトリ新規作成
                    %small
                      ※英数字, '-', '_' のみ使用可能
                  = render 'form'

#result

app/views/svns/show.html.haml
- title 'Repository Manager - Detail'

%section#svn-show
  .container{:style => "margin-top: 40px; padding-top: 10px"}
    .pageContent
      .show-svn
        .container
          .content
            .row
              .span12.offset2
                %h1
                  = params[:id]
                %table{:class => 'condensed-table bordered-table zebra-striped'}
                  %thead
                    %tr
                      %th{:style => 'style="width: 150px;'}
                        項目
                      %th
                        内容
                  %tbody
                    %tr
                      %td
                        ディレクトリ
                      %td
                        = "#{RailsApp::Application.config.svn_dir}/#{params[:id]}"
                    %tr
                      %td
                        リポジトリ
                      %td
                        = link_to 'http://' + RailsApp::Application.config.hostname + '/svn/' + params[:id], "/svn/" + params[:id]
                    %tr
                      %td
                        最終更新日
                      %td
                        = File::stat(RailsApp::Application.config.svn_dir + "/" + params[:id] + "/db/current").mtime

                .actions
                  = link_to '一覧へ戻る', repos_path, :class => 'btn small'
                  = link_to 'このリポジトリを削除する', params[:id], :data => { :confirm => '本当に削除しますか' }, :method => :delete, :class => 'btn small danger'